import { Project } from '@/app/projects/page';

export const mockProjects: Project[] = [
  {
    id: '1',
    slug: 'decentralized-finance-platform',
    name: 'DeFi Yield Optimizer',
    tagline: 'Maximize your DeFi yields across multiple protocols',
    description: 'A comprehensive DeFi platform that automatically optimizes yield farming strategies across Ethereum, Arbitrum, and Base networks. The platform uses advanced algorithms to identify the best yield opportunities and automatically rebalances positions for maximum returns.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '1',
    techStack: ['Solidity', 'React', 'TypeScript', 'Ethers.js'],
    finalScore: 95.5,
    rank: 1,
    prizeWon: 50000,
    status: 'WINNER',
    submittedAt: '2024-11-01T10:00:00Z',
    demoUrl: 'https://defi-yield-optimizer.demo',
    githubUrl: 'https://github.com/cryptodev/defi-yield-optimizer',
    videoUrl: 'https://youtube.com/watch?v=example1',
    creator: {
      id: '1',
      walletAddress: '0x1234567890123456789012345678901234567890',
      username: 'cryptodev',
    },
    hackathon: {
      id: '1',
      name: 'Web3 Africa Hackathon 2024',
    },
  },
  {
    id: '2',
    slug: 'nft-marketplace-africa',
    name: 'AfriNFT Marketplace',
    tagline: 'Empowering African artists in the digital economy',
    description: 'A decentralized NFT marketplace focused on showcasing African art and culture, with built-in royalty mechanisms and cross-chain support. Artists can mint, sell, and earn royalties on their digital creations.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '1',
    techStack: ['Next.js', 'IPFS', 'Web3.js', 'Polygon'],
    finalScore: 92.3,
    rank: 2,
    prizeWon: 30000,
    status: 'WINNER',
    submittedAt: '2024-11-01T11:00:00Z',
    demoUrl: 'https://afrinft-marketplace.demo',
    githubUrl: 'https://github.com/artblockchain/afrinft-marketplace',
    videoUrl: 'https://youtube.com/watch?v=example2',
    creator: {
      id: '2',
      walletAddress: '0x2345678901234567890123456789012345678901',
      username: 'artblockchain',
    },
    hackathon: {
      id: '1',
      name: 'Web3 Africa Hackathon 2024',
    },
  },
  {
    id: '3',
    slug: 'dao-governance-tool',
    name: 'DAO Governance Suite',
    tagline: 'Streamlined governance for decentralized organizations',
    description: 'A comprehensive governance platform for DAOs with voting mechanisms, proposal management, and treasury oversight. Enables transparent decision-making and efficient resource allocation.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '2',
    techStack: ['Vue.js', 'Solidity', 'GraphQL', 'The Graph'],
    finalScore: 88.7,
    rank: 3,
    prizeWon: 20000,
    status: 'WINNER',
    submittedAt: '2024-10-28T14:00:00Z',
    demoUrl: 'https://dao-governance.demo',
    githubUrl: 'https://github.com/daobuilder/governance-suite',
    videoUrl: 'https://youtube.com/watch?v=example3',
    creator: {
      id: '3',
      walletAddress: '0x3456789012345678901234567890123456789012',
      username: 'daobuilder',
    },
    hackathon: {
      id: '2',
      name: 'Base Ecosystem Hackathon',
    },
  },
  {
    id: '4',
    slug: 'cross-chain-bridge',
    name: 'Cross-Chain Bridge Pro',
    tagline: 'Seamless asset transfers across all EVM chains',
    description: 'A user-friendly bridge protocol enabling fast and secure transfers between Arbitrum, Base, and Optimism networks. Features low fees and instant confirmations.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '2',
    techStack: ['React', 'Solidity', 'Hardhat', 'Chainlink'],
    finalScore: 87.2,
    rank: 4,
    prizeWon: 15000,
    status: 'APPROVED',
    submittedAt: '2024-10-27T09:00:00Z',
    demoUrl: 'https://cross-chain-bridge.demo',
    githubUrl: 'https://github.com/bridgebuilder/cross-chain-bridge',
    videoUrl: 'https://youtube.com/watch?v=example4',
    creator: {
      id: '4',
      walletAddress: '0x4567890123456789012345678901234567890123',
      username: 'bridgebuilder',
    },
    hackathon: {
      id: '2',
      name: 'Base Ecosystem Hackathon',
    },
  },
  {
    id: '5',
    slug: 'smart-wallet-africa',
    name: 'Smart Wallet for Africa',
    tagline: 'Banking the unbanked with Web3 technology',
    description: 'A mobile-first smart wallet solution designed for low-bandwidth environments, enabling financial inclusion across Africa. Features offline support and minimal data usage.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '1',
    techStack: ['Flutter', 'Solidity', 'IPFS', 'PWA'],
    finalScore: 85.9,
    rank: 5,
    prizeWon: 10000,
    status: 'APPROVED',
    submittedAt: '2024-11-01T08:00:00Z',
    demoUrl: 'https://smart-wallet-africa.demo',
    githubUrl: 'https://github.com/fintechafrica/smart-wallet',
    videoUrl: 'https://youtube.com/watch?v=example5',
    creator: {
      id: '5',
      walletAddress: '0x5678901234567890123456789012345678901234',
      username: 'fintechafrica',
    },
    hackathon: {
      id: '1',
      name: 'Web3 Africa Hackathon 2024',
    },
  },
  {
    id: '6',
    slug: 'carbon-credit-marketplace',
    name: 'Carbon Credit Marketplace',
    tagline: 'Tokenizing carbon credits for transparent climate action',
    description: 'A blockchain-based marketplace for buying and selling carbon credits, with full transparency and verification. Enables companies and individuals to offset their carbon footprint through verified credits.',
    coverImage: '/placeholder-project.jpg',
    hackathonId: '3',
    techStack: ['Next.js', 'Solidity', 'Chainlink', 'OpenZeppelin'],
    status: 'UNDER_REVIEW',
    submittedAt: '2024-11-03T16:00:00Z',
    demoUrl: 'https://carbon-credit-marketplace.demo',
    githubUrl: 'https://github.com/climatechain/carbon-credits',
    videoUrl: 'https://youtube.com/watch?v=example6',
    creator: {
      id: '6',
      walletAddress: '0x6789012345678901234567890123456789012345',
      username: 'climatechain',
    },
    hackathon: {
      id: '3',
      name: 'Climate Tech Hackathon',
    },
  },
];

export function findMockProjectBySlug(slug: string): Project | undefined {
  return mockProjects.find((project) => project.slug === slug);
}

