import { Lesson } from '@/app/learn/page';

export const mockLessons: Lesson[] = [
  {
    id: '1',
    slug: 'solidity-basics',
    title: 'Solidity Fundamentals',
    description: 'Learn the basics of Solidity programming language, including variables, functions, modifiers, and events. This comprehensive course covers everything you need to start writing smart contracts on Ethereum and EVM-compatible chains.',
    category: 'smart-contracts',
    difficulty: 'beginner',
    duration: 45,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=solidity-basics',
    author: {
      name: 'Web3 Africa',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Solidity', 'Smart Contracts', 'Ethereum'],
    views: 12500,
    rating: 4.8,
  },
  {
    id: '2',
    slug: 'defi-yield-farming',
    title: 'DeFi Yield Farming Strategies',
    description: 'Master yield farming strategies across multiple DeFi protocols on Arbitrum, Base, and Optimism. Learn how to identify the best opportunities, manage risk, and optimize returns.',
    category: 'defi',
    difficulty: 'intermediate',
    duration: 60,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=defi-yield-farming',
    author: {
      name: 'DeFi Expert',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['DeFi', 'Yield Farming', 'Arbitrum', 'Base'],
    views: 8900,
    rating: 4.9,
  },
  {
    id: '3',
    slug: 'nft-marketplace-development',
    title: 'Build an NFT Marketplace',
    description: 'Create a fully functional NFT marketplace from scratch using React, Solidity, and IPFS. Learn how to implement minting, buying, selling, and royalty mechanisms.',
    category: 'nft',
    difficulty: 'advanced',
    duration: 120,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=nft-marketplace',
    author: {
      name: 'NFT Builder',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['NFT', 'ERC-721', 'IPFS', 'React'],
    views: 15200,
    rating: 4.7,
  },
  {
    id: '4',
    slug: 'dao-governance',
    title: 'DAO Governance Best Practices',
    description: 'Learn how to structure and govern decentralized autonomous organizations effectively. Cover voting mechanisms, proposal systems, treasury management, and community engagement.',
    category: 'dao',
    difficulty: 'intermediate',
    duration: 50,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=dao-governance',
    author: {
      name: 'DAO Architect',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['DAO', 'Governance', 'Voting', 'Treasury'],
    views: 6700,
    rating: 4.6,
  },
  {
    id: '5',
    slug: 'hardhat-testing',
    title: 'Smart Contract Testing with Hardhat',
    description: 'Comprehensive guide to writing and running tests for your smart contracts using Hardhat. Learn unit testing, integration testing, and best practices for test coverage.',
    category: 'smart-contracts',
    difficulty: 'intermediate',
    duration: 55,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=hardhat-testing',
    author: {
      name: 'Smart Contract Dev',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Hardhat', 'Testing', 'JavaScript', 'Smart Contracts'],
    views: 9800,
    rating: 4.8,
  },
  {
    id: '6',
    slug: 'wagmi-web3-integration',
    title: 'Web3 Integration with Wagmi',
    description: 'Connect your React app to Ethereum and L2 networks using Wagmi and Viem. Learn how to handle wallet connections, read blockchain data, and send transactions.',
    category: 'frontend',
    difficulty: 'beginner',
    duration: 40,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=wagmi-web3',
    author: {
      name: 'Frontend Dev',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Wagmi', 'React', 'Web3', 'Viem'],
    views: 11200,
    rating: 4.9,
  },
  {
    id: '7',
    slug: 'cross-chain-bridge',
    title: 'Cross-Chain Bridge Development',
    description: 'Build a cross-chain bridge to transfer assets between Arbitrum, Base, and Optimism. Learn about bridge architecture, security considerations, and implementation details.',
    category: 'infrastructure',
    difficulty: 'advanced',
    duration: 90,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=cross-chain-bridge',
    author: {
      name: 'Infrastructure Expert',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Cross-Chain', 'Bridge', 'Arbitrum', 'Base', 'Optimism'],
    views: 5400,
    rating: 4.5,
  },
  {
    id: '8',
    slug: 'hackathon-success',
    title: 'Winning Your First Hackathon',
    description: 'Strategies and tips for building and presenting winning projects at Web3 hackathons. Learn how to form teams, manage time, create compelling demos, and pitch effectively.',
    category: 'hackathons',
    difficulty: 'beginner',
    duration: 35,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=hackathon-success',
    author: {
      name: 'Hackathon Winner',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Hackathons', 'Strategy', 'Pitching', 'Teamwork'],
    views: 18900,
    rating: 4.9,
  },
  {
    id: '9',
    slug: 'security-best-practices',
    title: 'Smart Contract Security',
    description: 'Common vulnerabilities and best practices for writing secure smart contracts. Learn about reentrancy attacks, overflow/underflow, access control, and how to prevent common exploits.',
    category: 'security',
    difficulty: 'advanced',
    duration: 70,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=security-best-practices',
    author: {
      name: 'Security Auditor',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Security', 'Auditing', 'Best Practices', 'Vulnerabilities'],
    views: 14300,
    rating: 5.0,
  },
  {
    id: '10',
    slug: 'foundry-development',
    title: 'Foundry Development Workflow',
    description: 'Complete guide to using Foundry for smart contract development, testing, and deployment. Learn Forge, Cast, Anvil, and Chisel to build and deploy production-ready contracts.',
    category: 'smart-contracts',
    difficulty: 'intermediate',
    duration: 65,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=foundry-development',
    author: {
      name: 'Foundry Expert',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Foundry', 'Forge', 'Testing', 'Deployment'],
    views: 7600,
    rating: 4.7,
  },
  {
    id: '11',
    slug: 'token-standards',
    title: 'ERC Token Standards Explained',
    description: 'Deep dive into ERC-20, ERC-721, ERC-1155, and other token standards on Ethereum. Learn when to use each standard and how to implement them correctly.',
    category: 'smart-contracts',
    difficulty: 'intermediate',
    duration: 50,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=token-standards',
    author: {
      name: 'Token Standards Expert',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['ERC-20', 'ERC-721', 'ERC-1155', 'Standards'],
    views: 10200,
    rating: 4.8,
  },
  {
    id: '12',
    slug: 'africa-web3-opportunities',
    title: 'Web3 Opportunities in Africa',
    description: 'Exploring unique opportunities and use cases for blockchain technology in African markets. Learn about financial inclusion, remittances, supply chain, and identity solutions.',
    category: 'business',
    difficulty: 'beginner',
    duration: 30,
    thumbnail: '/placeholder-lesson.jpg',
    videoUrl: 'https://youtube.com/watch?v=africa-web3',
    author: {
      name: 'Web3 Africa',
      avatar: '/placeholder-avatar.jpg',
    },
    tags: ['Africa', 'Use Cases', 'Business', 'Opportunities'],
    views: 15600,
    rating: 4.9,
  },
];

export function findMockLessonBySlug(slug: string): Lesson | undefined {
  return mockLessons.find((lesson) => lesson.slug === slug);
}

